### ISSUE TITLE
Advanced sound option capability?

### ISSUE THREAD

**Issue by Laberbear** [marcjoha/AudioSwitcher#3]
Hey Marcjoha,
I really love this little project. It is just one of the things Microsoft should've thought about themselves.

However my sound setup is bit more complicated and I would love to know if you think there is a way automate my sound switch aswell:
A few programs really don't like the regular switching between audio devices (some crash, some just don't bother and use the other one). That's why I use my soundcard always as my default sound device and then just change the 'Listen to this device' capability of Windows to switch between headphones and my TV. (The attached screenshot may show it a little bit better, sorry for the German)
![sound](https://cloud.githubusercontent.com/assets/10895804/7124026/7d3028b8-e226-11e4-9c7b-04dac28d2917.png)

So I'm currently thinking of a way to automate the tedious sound switching process. Do you think that there is a possibility to change such 'advanced' features?

**Comment by marcjoha** [comment]
Hi Laderbear,

Sorry to say I don't know. This tool is really coming from the other direction; I was fed up with the 'Listen to this device' functionality as I felt it rarely worked. That's why I resorted to messing with the default output device. But you're right, that's not ideal either. Windows actually don't like this at all; MS actively discourages it and don't provide any tools to do this which is why this project is using an unofficial API which was reverse engineered by a 3rd party.
